<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.6*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DRGSContracts.Terminal\DRGSContracts.Terminal.csproj" />
  </ItemGroup>

</Project>
